// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: point2i.proto

#ifndef PROTOBUF_point2i_2eproto__INCLUDED
#define PROTOBUF_point2i_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)

namespace flib {
namespace proto {

// Internal implementation detail -- do not call these.
void FACELIBSHARED_EXPORT protobuf_AddDesc_point2i_2eproto();
void protobuf_AssignDesc_point2i_2eproto();
void protobuf_ShutdownFile_point2i_2eproto();

class Point2i;

// ===================================================================

class FACELIBSHARED_EXPORT Point2i : public ::google::protobuf::Message {
 public:
  Point2i();
  virtual ~Point2i();

  Point2i(const Point2i& from);

  inline Point2i& operator=(const Point2i& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Point2i& default_instance();

  void Swap(Point2i* other);

  // implements Message ----------------------------------------------

  Point2i* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Point2i& from);
  void MergeFrom(const Point2i& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);

  // required int32 y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:flib.proto.Point2i)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  friend void FACELIBSHARED_EXPORT protobuf_AddDesc_point2i_2eproto();
  friend void protobuf_AssignDesc_point2i_2eproto();
  friend void protobuf_ShutdownFile_point2i_2eproto();

  void InitAsDefaultInstance();
  static Point2i* default_instance_;
};
// ===================================================================


// ===================================================================

// Point2i

// required int32 x = 1;
inline bool Point2i::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Point2i::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Point2i::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Point2i::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Point2i::x() const {
  // @@protoc_insertion_point(field_get:flib.proto.Point2i.x)
  return x_;
}
inline void Point2i::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:flib.proto.Point2i.x)
}

// required int32 y = 2;
inline bool Point2i::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Point2i::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Point2i::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Point2i::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Point2i::y() const {
  // @@protoc_insertion_point(field_get:flib.proto.Point2i.y)
  return y_;
}
inline void Point2i::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:flib.proto.Point2i.y)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace flib

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_point2i_2eproto__INCLUDED
